### ISSUE TITLE
Download stops with message MP2T failure

### ISSUE THREAD

**Issue by Tkkg1994** [DoctorLai/VideoDownloadHelper#38]
Hello and thanks very much for your awesome tool!

I try to download a video. I do following steps:
1. Go to the website (in this case it's on servusTV)
2. Click on download and choose the path on my HDD
3. The file loads fine till 100%
4. At the end nothing happens and following error appears:

```
Error: MP2T - No data received
    at t.value (chrome-extension://lmjnegcaeklhafolokijcfjliaokphfk/background/main.js:1:157193)
    at t.value (chrome-extension://lmjnegcaeklhafolokijcfjliaokphfk/background/main.js:1:145961)
    at t.value (chrome-extension://lmjnegcaeklhafolokijcfjliaokphfk/background/main.js:1:80968)
    at chrome-extension://lmjnegcaeklhafolokijcfjliaokphfk/background/main.js:1:145103
```

If you could help me out here I'd be very happy!

**Comment by DoctorLai** [comment]
can't reproduce
